name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: aashish108/darshan-cms/darshan-cms-docker-image:latest
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
        registry: docker.pkg.github.com
